# Generated by Django 5.1.7 on 2025-04-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='codigo_acesso',
            field=models.CharField(default=123, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
